name: 'C++ CI'

on:
  push:
    branches:
      - hw004
      - feature/github_actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: sudo apt-get update && sudo apt-get install doxygen -y
      - run: cmake .
      - run: cmake --build .
      - run: cmake --build . --target package
      - run: ./hw004
      - run: doxygen
